# Generated by Django 3.2.12 on 2023-04-16 11:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=100000)),
                ('answer', models.CharField(max_length=1000000)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('filename', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Request',
            },
        ),
        migrations.AlterField(
            model_name='resume',
            name='Report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.report', verbose_name='Report'),
        ),
    ]
