# Generated by Django 3.2.12 on 2023-03-30 11:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('file', models.FileField(upload_to='medias/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Video',
            },
        ),
        migrations.CreateModel(
            name='TextGen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('Audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AudioToText.audio', verbose_name='Audio')),
            ],
            options={
                'verbose_name_plural': 'TextGen',
            },
        ),
    ]
